### ISSUE TITLE
Plotting methods

### ISSUE THREAD

**Issue by njtierney** [njtierney/mmcc#16]
Add a joyplot method?

https://twitter.com/mikedecr/status/886376620004700160

**Comment by samclifford** [comment]
If you can facet a joyplot you could have a facet by parameter group and everything without a group either gets lumped together into one group or shown on its own.

**Comment by njtierney** [comment]
Thinking about this further I think that plotting should happen outside this package, I would prefer to keep this as a package that just does data structures - any thoughts here @samclifford?

**Comment by samclifford** [comment]
I'm okay with keeping it light and focussing on manipulating data objects.
