### ISSUE TITLE
Thoughts on what is needed before we put this onto CRAN?

### ISSUE THREAD

**Issue by njtierney** [njtierney/mmcc#23]
What do you reckon, @samclifford ?

It would be great if we could submit this for publication somewhere, perhaps JOSS or similar.

The remaining issues to be tackled include:

* #19 - Create fast diagnostic functions (replacing `coda`'s diagnostics)
* ~#22 - import `generics` instead of broom~
* #18 - Clear up ideas on augment/glance/tidy

The earliest I'll be able to commit serious hours to this will be around Jan 25 2019, let me know what you think.

**Comment by samclifford** [comment]
Good project for the new year. Agree that these are the priorities. Hadn't seen `generics` but agree that it's a good idea.

**Comment by njtierney** [comment]
Awesome!

We could also, now, big blue sky idea here, come up with other metrics for convergence and include these in `mmcc`.

**Comment by njtierney** [comment]
OK so I'm going to close this since this is kind of a meta description on what we need to do.
