### ISSUE TITLE
Think about renaming the package

### ISSUE THREAD

**Issue by njtierney** [njtierney/mmcc#4]
OK @MilesMcBain and @samclifford

Here's a space for us to nut out some names

Current contenders:
- mcmcspyder: something that crawls along gets information and produces something
- mcmcscarab: mcmc scarab - something that gathers shit and makes it useful
- codetta: small coda at the end of a piece. What you do after a coda.
- bdsmcmc: Make it fun to get the chains and ropes out of mcmc

And I think that's it so far?

**Comment by njtierney** [comment]
other potential names:

- mcmcstory

It's about getting the story from the mcmc, and the data. It's also a little reference to the Story Bridge, in Brisbane.

- mcmchammer

If nothing for the name? Where plyr invokes the idea of a set of pliers, mcmchammer is a tool that hits mcmc and make stuff fall out. Kinda blunt. But effective?

But I feel like mcmchammer should have a better use rather than some sort of lightweight data reshaping and investigation tool.

**Comment by samclifford** [comment]
If it's all about reshaping and manipulating mcmc chains, why not mmcc?

**Comment by njtierney** [comment]
I like that a lot!

**Comment by samclifford** [comment]
Any decision on this?

**Comment by njtierney** [comment]
I'd be pretty happy with `mmcc`, did you want to have a crack at changing the name? Otherwise I'm happy to :)

**Comment by samclifford** [comment]
You go ahead.

**Comment by njtierney** [comment]
OK sure, probably best that you merge the PR before we change the name though

**Comment by njtierney** [comment]
Done! And we have a website as well!
